# This is the configuration file for a Dart DHCP & DNS server.
# For each interface, you can specify whether DHCP is enabled or not.
# While the DNS server is always enabled.

# This configuration contains 3 interfaces: ens32, ens37, ens33.
# ens33 is in cn. domain, ens32 is in sh.cn domain, ens37 is in sh.cn domain.
# This host serves as the DHCP & DNS server for the 2 domains: bj.cn and sh.cn.
# (and even the gateway for bj.cn and sh.cn, but this daemon does not do that)
# Domain cn is the parent domain of bj.cn and sh.cn.

# When a DHCP client in bj.cn or sh.cn applies for an IP address, this daemon will 
# answer it. And at the same time, the daemon will remember whether the client 
# supports Dart protocol or not. 

# If a DNS query packet arrives, this daemon will check whether the querier and 
# the queried party are in the same domain.
# If they are, it will return the IP address assigned by the DHCP service. 
# If not, it will return the IP address of this server's interface in the same domain.
# In other words, this server will forward packets between different domains. 
# (This will be handled by another forwarding program.)

interfaces:
  - name: ens32
    direction: downlink
    address_pool: 10.1.0.100-10.1.0.200
    domain: bj.cn
    gateway: 10.1.0.1
    dns_servers:
      - 10.1.0.1
      
  - name: ens37
    direction: uplink
    address_pool: 10.0.0.100-10.0.0.200
    domain: sh.cn
    gateway: 10.0.0.1
    dns_servers:
      - 10.0.0.1
    static_bindings:
      - mac: "00:0c:29:f1:65:17"
        ip: "10.0.0.99"

  - name: ens33
    direction: uplink
    domain: cn
    dns_servers:
      - 192.168.1.1
        8.8.8.8