name: dart_dhcpd
description: A custom DHCP server implementation in Dart.
version: 1.0.0

environment:
  # sdk: '>=2.14.0 <3.0.0'
  sdk: ^3.5.0

dependencies:
  ffi: ^2.0.1
  yaml: ^3.1.0
  sqlite3: ^1.8.0
  dart_dns: 
    path: packages/dns
